spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pay-center
    username: root
    password: root
    max-idle: 10
    min-idle: 5
    max-wait: 10000
    initial-size: 5
    driver-class-name: com.mysql.cj.jdbc.Driver