spring:
  mvc:
    static-path-pattern: /static/**

  ##datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pay-center?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  ##freemarker
  freemarker:
    cache: false
    check-template-location: true
    charset: utf-8
    suffix: .ftl

  ##rabbitmq
  rabbitmq:
    host: 106.13.15.246
    port: 5672
    username: pay_guest
    password: pay_guest
    virtual-host: /pay
    publisher-confirms: true

mybatis:
  mapper-locations: /mapper/*.xml
  configuration:
    ##启用从数据库列名A_COLUMN到驼峰大小写Java属性名aColumn的自动映射。
    map-underscore-to-camel-case: true
    ##允许JDBC支持生成的键
    use-generated-keys: true
    ##开启日志打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
